server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true



logging:
  level:
    org:
      hibernate:
        sql: debug


jwt:
  sign_key: "rG2Wp80h/2q/ZoxaaVmk1FwQijr+RElHiheKIB5fBLjZNd+8Yhft9yjG1HxX+TPG"